# Consumes the bluesky firehose
pipeline:
  batch_size: 1
  source:
    type: websocket
    websocket:
      uri: 'wss://jetstream2.us-east.bsky.network/subscribe?wantedCollections=app.bsky.feed.post'

  handler:
    type: 'handlers.InferredMemBatch'
    sql: |
      SELECT * FROM batch

  sink:
    type: kafka
    kafka:
      brokers: [localhost:9092]
      topic: output-bluesky-firehose
